### ISSUE TITLE
Sensor failed event  (SF: #14 )

### ISSUE THREAD

**Issue by alco28** [weewx/weewx#2]
Add an event SENSOR_FAILED or something similar, to signal problems with a sensor or station.

[Note: pulled from sourceforge issue 14 ](https://sourceforge.net/p/weewx/tickets/14/)

**Comment by alco28** [comment]
Should then result in a long sleep and retry. (comment from Tom Keffer)

**Comment by tkeffer** [comment]
I'm not sure where this issue came from. Do we really want an event? Or, an exception? If the former, what would be the consumer, and why does it need to consume an event instead of an exception? If the latter, we already have similar exceptions:

`weewx.WeeWxIOError`. If raised, weewx will wait 60 seconds, then restart.
`weewx.HardwareError`. This causes program termination.

I'm not seeing the utility, so I'm closing this unless someone says otherwise.
