### ISSUE TITLE
One week plot aggregations should start on Sunday

### ISSUE THREAD

**Issue by tkeffer** [weewx/weewx#279]
Presently, weekly plots show an aggregation over seven days, but the start day is almost arbitrary --- it's effectively the present day.

It should consistently aggregate starting on Sunday (or whatever is the locale's start of the week)

**Comment by gjr80** [comment]
I am a little lost on this one, by saying:

> but the start day is almost arbitrary --- it's effectively the present day.

I presume you mean the current day of the week one week ago ie if today is Wednesday the 11th the start is Wednesday the 4th?

> It should consistently aggregate starting on Sunday (or whatever is the locale's start of the week)

Are you saying that if generated on a Wednesday the 'week' plot should have no more than 5 days (assuming of course that Sunday is used as the start of the week) of data plotted? This would seem to me to provide somewhat of an odd plot.

Perhaps I am missing the obvious, or something particularly subtle, but I am having trouble seeing the real issue here. I accept there is an inconsistency between a tag with an aggregation period of 1 week eg `$week.rain.sum` and what are known as the 'weekly' or 'week' plots. The former shows data since (usually) Sunday whereas the latter shows data over the last 7+ days. 

Would not the same issue exist for month and year? Maybe we could just change what we call the 'week' plots, perhaps '7 day' plots.

Of course if I have missed the issue completely....

**Comment by tkeffer** [comment]
Sorry, I wasn't very clear, and my diagnosis was a bit off.

If you ask for a month plot with daily aggregations, you get this:
![image](https://user-images.githubusercontent.com/3321259/31323586-9766b2ec-ac5e-11e7-9dcb-a38b31f816b5.png)

Note how all aggregations start and end at midnight. If you try it for a week plot, you get this:

![image](https://user-images.githubusercontent.com/3321259/31323608-f18b2546-ac5e-11e7-963c-a56b656fa447.png)

Note how the weeks do not start on Sunday. They start on a Thursday.

**Comment by gjr80** [comment]
Ok, understand, I took weekly plots to mean plots that cover 1 week in total where in fact the issue is the aggregattion period.
