### ISSUE TITLE
wiki page for transfer from sqlite to mysql has invalid `wee_database --backfill-daily --binding=dest_binding`

### ISSUE THREAD

**Issue by gearoidgit** [weewx/weewx#286]
The wiki [page](https://github.com/weewx/weewx/wiki/Transfer%20from%20sqlite%20to%20MySQL) has an invalid `wee_database --backfill-daily ` example.
Is there a way to to a transfer of the daily summaries to a new mySQL database ?
I'm happy to correct the wiki if there's a way to do this or if not to remove the section.

**Comment by gjr80** [comment]
You are correct, the `wee_database` utility received a makeover in v3.7.0 and the `--backfill-daily` action was renamed `--rebuild-daily`. For the purposes of the SQLite to MySQL wiki entry it is simply a case of using `wee_database --rebuild-daily` Instead of `wee_database --backfill-daily`.

Anybody with a github account should be able to edit the wiki, so feel free to fix the error.

Just to clarify one point, `wee_database` does not actually transfer the daily summaries from one database to another, rather it rebuilds the daily summaries of the database referred to by the binding `db_binding` in `weewx.conf` (or the `wee_database` option `--binding` if used) from the archive data in the same database.

**Comment by gearoidgit** [comment]
I've updated the wiki [section](https://github.com/weewx/weewx/wiki/Transfer-from-sqlite-to-MySQL#using-wee_database).  If another contributor reckons it's now correct I'll close this issue

**Comment by gjr80** [comment]
There are two occurrences of `--backfill-daily` just above the heading 'Using wee_database', you might as well update those as well. I also noticed another unrelated typo; the reference to `archive_sqlite` in the second para after the 'Using wee_database' heading should in fact be `archive_mysql`. Would be appreciated if you fixed that one as well. Otherwise looks good to me.

**Comment by gearoidgit** [comment]
I've completed those, I see `--backfill-daily` is also in the MySQL->sqlite page so I'll correct that too.

**Comment by gjr80** [comment]
Looks good. Thanks very much for your help.
