### ISSUE TITLE
Refactor logging into a single facility

### ISSUE THREAD

**Issue by tkeffer** [weewx/weewx#353]
We use many different logging strategies across the code base. They should be refactored into a single one, then used  consistently.

**Comment by matthewwall** [comment]
here are some use cases to help guide the evaluation of options:

1) log level.  these levels are most commonly used in weewx:

* error - something failed that user should know about
* info - feedback about settings and/or operation
* debug - detailed feedback

additional levels such as fatal (fail that requires shutdown) or warn (a mild error?) are probably not necessary to distinguish?

2) do not repeat if not necessary.

3) lots of logging when setting up, but change to log-only-exceptions after configuration is tuned.  default behavior should be to provide good feedback, but it should be easy to switch to log-exceptions.  example is the `log_success` and `log_failure` pattern for uploaders.  use case is low-write scenarios (e.g., on SD/SATA-DOM applications) and low-disk-space scenarios (e.g., tiny /var/log partition on a router)

4) driver diagnostic logging (e.g., every string of bytes to/from device).  some drivers need multiple levels of diagnostics, e.g., serial-comms vs parsing-of-serial-data vs loop/archive.  the pattern of debug_xxx withing the driver's config stanza has been used in many drivers to provide these distinctions.

5) uploader diagnostic logging.  uploaders need simple log entry to indicate that upload succeeded/failed.  also need ability to do detailed logging, e.g., actual data sent in a packet/url.

6) consistency - use consistent patterns in the log message formats to make it easy to write patterns for logwatch or elastic search.  for example, put entire log message into a single line whenever possible, but if must use multi-line then do it in a way that can be post-processed easily.

7) platform-agnostic.  we should consider using the python `logging` module instead of using syslog.  

8) logging shim.  whether we use `logging` or `syslog`, we will probably need a thin shim to (1) configure the log and (2) to reduce the amount of code that developers need to write in order to make log entries.  the `logdbg`, `loginf`, `logerr` pattern results in compact, easy-to-manage log management, but probably could be done more pythonically.  doing `syslog.syslog(syslog.LOG_ERR, msg)` is too verbose imho.  the python pattern of `logger.info(msg)` has worked well for me in other projects, and it comes with the benefit of getting module/function labels in log messages if you configure the logger correctly.

**Comment by tkeffer** [comment]
In this issue, I had intended only to take on your use case 8. I've made a start in commit https://github.com/weewx/weewx/commit/a930e65c0024b3738084b5dc10a6f422b790a0a3.

Your wish list, while good, is sprawling! We should open up other issues for its individual items.

**Comment by tkeffer** [comment]
Instead of a logging shim, I've switched to using the Python `logging` package with commit https://github.com/weewx/weewx/commit/f90dd8ab7ed82042f4c99066716e6906a3947cf7 (and others).

**Comment by ke6jjj** [comment]
Hey @tkeffer , I'm looking to make a WeeWX extension that supports both WeeWX 3 and WeeWX 4. What's the recommended way to query whether my extension should use logging as well or revert to direct syslog calls?

**Comment by ke6jjj** [comment]
After checking the commits for this feature, it looks like trying to import `weeutil.log` might be a good way to tell. If that fails then I'll use syslog.

**Comment by ke6jjj** [comment]
I found more info in `docs/logging.md`, specifically under `Maintaining backwards compatibility`. Thanks for the documentation!

**Comment by gjr80** [comment]
> Hey @tkeffer , I'm looking to make a WeeWX extension that supports both WeeWX 3 and WeeWX 4. What's the recommended way to query whether my extension should use logging as well or revert to direct syslog calls?

Hi, probably more appropriate for the weewx-development group rather than a closed issue that has limited visibility. But you might want to look at some of the older drivers/extensions that are [listed in the wiki](https://github.com/weewx/weewx/wiki#extensions-to-weewx) as being WeeWX 4 compatible. Some of these extensions/drivers have been updated to work with both WeeWX 3 and WeeWX 4 logging. The interceptor driver is one such example.
