### ISSUE TITLE
Investigate whether daemonize() is still useful

### ISSUE THREAD

**Issue by tkeffer** [weewx/weewx#360]

**Comment by matthewwall** [comment]
here is some background reading:

https://www.python.org/dev/peps/pep-3143/

some of the features that you get with daemonizing: chroot, explicit list of signals, uid/gid, stderr/stdout control, working directory.

could be problematic since default behavior is "there can be only one"

could cause problems on windows - it is one more layer of code to deal with, and windows 'services' are explicitly *not* unix daemons.

**Comment by tkeffer** [comment]
It appears `daemonize()` is still useful.
