### ISSUE TITLE
ImportError: no module named weewx.drivers

### ISSUE THREAD

**Issue by richardh9935** [weewx/weewx#476]
I am using macOS Catalina.

I followed your instructions but directly invoking sdr.py failed with this message: 
File "/Users/Shared/weewx/bin/user/sdr.py", line 91, in <module>
    import weewx.drivers
ImportError: No module named weewx.drivers

I searched my file system but could not find weewx.drivers, although a directory called drivers does exist below a directory called weewx.

I re-started by following your installation process again, but I still failed with the above error.

Do you think this could be a PATH or PYTHONPATH error?

echo $PYTHONPATH
/Users/Shared/weewx-sdr/bin/user:/Users/Shared/rtl-sdr:/Users/Shared/rtl_433:/Users/Shared/weewx:/usr/local/lib/python2.7

richard@RLHMacmini Shared % echo $PATH
/usr/local/share/python2.7/:/Users/Shared/rtl_433:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Shared/weewx:/Users/Shared/weewx/bin:/opt/X11/bin

**Comment by tkeffer** [comment]
Definitely a `PYTHONPATH` problem.

It looks like you installed weewx in `/Users/Shared/weewx`. If so, to run `sdr.py` directly you will need

```shell
cd /Users/Shared/weewx
PYTHONPATH=bin python ./bin/user/sdr.py
```
The reason is that, by default, python will only search directories directly below the "executable," in this case, `./bin/user/sdr.py`. So you have to explicitly tell it where to find things.

The `drivers` directory is located at `/Users/Shared/weewx/bin/weewx/drivers`

Incidentally, in the future, for support questions, please post to [`weewx-user`](https://groups.google.com/forum/#!forum/weewx-user). The Issues list is for bug tracking.
