### ISSUE TITLE
ssl.CertificateError is not available on earlier Python 2.7 versions

### ISSUE THREAD

**Issue by zeroepoch** [weewx/weewx#569]
In `bin/weewx/restx.py` you are catching an exception of type `ssl.CertificateError`, but that class doesn't appear to be available in Python 2.7.3, at least not on my Intel Edison device. The exception class `ssl.SSLError` is provided though. I have changed the line to catch `ssl.SSLError` instead and it appears to keep the threads alive, but I don't know for sure that it works correctly and I haven't tried to generate the error on purpose. If we were able to update that line we could support more Python 2.7 versions.

**Comment by tkeffer** [comment]
Fixed, I think, in commit https://github.com/weewx/weewx/commit/dbcd1d1da2de821c99b0db05bfffd76bea2b8726

Instead of catching just `ssl.CertificateError`, it now catches all `ssl.SSLError`. This means other SSL errors, besides certificate errors, will be caught.

Reflecting this, I've changed the option name from `retry_certificate` to `retry_ssl`. If you use the updated version, please change your `weewx.conf` accordingly.
