### ISSUE TITLE
accented chars in comments kill weewx reporting

### ISSUE THREAD

**Issue by sbsrouteur** [weewx/weewx#639]
After upgrading ton v4.3.0 and porting my settings to weewx.conf, I found that weewx was not generating the reports.

(see post on group for error details : [report](https://groups.google.com/g/weewx-user/c/LIPWn-kOTls)

Eventually found that I pasted a comment from my v3.9.1 that had a à char (unicode 0xE0).

The accented char in comment was in :
`##############################################################################

#   This section can adjust data using calibration expressions.

[StdCalibrate]
    
    [[Corrections]]
        # For each type, an arbitrary calibration expression can be given.
        # It should be in the units defined in the StdConvert section.
        # Example:
        foo = foo + 0.2
	# -1.33 à 1.72?? -2.3 à 990mb (mes 1068)
        pressure = (pressure - 2.3)
`

Removing the accented chars fixed the issue.

**Comment by tkeffer** [comment]
I saw your post in weewx-user, and I was thinking the same thing. I have been able to replicate the error under Python 2.7.

Fixed in commit https://github.com/weewx/weewx/commit/624fb9e9fa1918491dcd6842683510c4211d9270

To fix, either remove the comment, or replace your copy of `/usr/share/weewx/weeutil/config.py` with this version: https://raw.githubusercontent.com/weewx/weewx/master/bin/weeutil/config.py
