### ISSUE TITLE
WMR300: Signal Quality shows bogus values

### ISSUE THREAD

**Issue by poohbeth** [weewx/weewx#641]
Just upgraded to 4.3.0 and appreciated the new graphs of inside humidity and signal quality. Trouble is the latter is currently showing 537% and drawing outside the actual graph. 

I couldn't see anything in syslog, or running it from a terminal, no mention anywhere. 

The sensor map just for info. 
Jan 19 11:14:32 roo weewx[16422] INFO weewx.drivers.wmr300: sensor map is {'pressure': 'pressure', 'barometer': 'barometer', 'windSpeed': 'wind_avg', 'windDir': 'wind_dir', 'windGust': 'wind_gust', 'windGustDir': 'wind_gust_dir', 'inTemp': 'temperature_0', 'outTemp': 'temperature_1', 'extraTemp1': 'temperature_2', 'extraTemp2': 'temperature_3', 'extraTemp3': 'temperature_4', 'extraTemp4': 'temperature_5', 'extraTemp5': 'temperature_6', 'extraTemp6': 'temperature_7', 'extraTemp7': 'temperature_8', 'inHumidity': 'humidity_0', 'outHumidity': 'humidity_1', 'extraHumid1': 'humidity_2', 'extraHumid2': 'humidity_3', 'extraHumid3': 'humidity_4', 'extraHumid4': 'humidity_5', 'extraHumid5': 'humidity_6', 'extraHumid6': 'humidity_7', 'extraHumid7': 'humidity_8', 'dewpoint': 'dewpoint_1', 'extraDewpoint1': 'dewpoint_2', 'extraDewpoint2': 'dewpoint_3', 'extraDewpoint3': 'dewpoint_4', 'extraDewpoint4': 'dewpoint_5', 'extraDewpoint5': 'dewpoint_6', 'extraDewpoint6': 'dewpoint_7', 'extraDewpoint7': 'dewpoint_8', 'heatindex': 'heatindex_1', 'extraHeatindex1': 'heatindex_2', 'extraHeatindex2': 'heatindex_3', 'extraHeatindex3': 'heatindex_4', 'extraHeatindex4': 'heatindex_5', 'extraHeatindex5': 'heatindex_6', 'extraHeatindex6': 'heatindex_7', 'extraHeatindex7': 'heatindex_8', 'windchill': 'windchill', 'rainRate': 'rain_rate'}

Example - 
![Screenshot_20210119_213812](https://user-images.githubusercontent.com/55546319/105096583-388d0d00-5a9f-11eb-85f6-2e56a179200b.png)

**Comment by CameronD73** [comment]
The WMR300 has no signal quality value that I can decipher, so I was using that parameter as a debug channel.
It should only receive a value if DEBUG_HISTORY is enabled, which you should not need.  Otherwise I would have expected the database field to be null and nothing plotted.
I never noticed the issue as I have a stripped-down database without such fields.

immediate (11 months late) solution is to disable debug statements (unless you are having other problems with the driver - in which case follow through with me).  
If you feel inclined you could set the contents of the rxCheckPercent field to NULL - but I don't feel competent to advise on sql statements if you don't know what to do already.
Also, I have stripped down Seasons skin files to remove unused fields/graphs.

Sorry I never noticed this - I had been following the group mailing list but not this.
